# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4dad3bb0b439ab12319593b4cf0f00fcfeb310a20a1ccbfed4b808bfb81b285ffbaf125a5233fc051b44ddde6170d2a04f917d65ccceb685ff74e47aec9dea77

test:
  secret_key_base: c8f737be03e577aecb74ad9e87348991b8c98622c85a2238f4b4b5be4264a7d8d09a79eb78eab38c695dfb7be9bd4c513b164e3613b5d8fb08faf7db94186bb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
